"""Initial migration

Revision ID: 1e3fdb966f0c
Revises: 
Create Date: 2025-05-06 16:38:25.258137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e3fdb966f0c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('height', sa.Float(), nullable=True))
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user', 'height')
    op.drop_column('user', 'weight')
    op.drop_column('user', 'age')
    # ### end Alembic commands ###
