"""Update user schema

Revision ID: 3828f1e635de
Revises: 36d339db9b56
Create Date: 2025-05-19 13:11:27.828806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '3828f1e635de'
down_revision: Union[str, None] = '36d339db9b56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('assigned_user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True))
    op.create_foreign_key(None, 'task', 'user', ['assigned_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'assigned_user_id')
    # ### end Alembic commands ###
