"""Update tasks schema

Revision ID: 67583ff4c201
Revises: 3828f1e635de
Create Date: 2025-05-19 14:14:33.872655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '67583ff4c201'
down_revision: Union[str, None] = '3828f1e635de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_task_answer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('selected_option_ids', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('text_answer', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('task_option_task_id_fkey', 'task_option', type_='foreignkey')
    op.drop_column('task_option', 'task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_option', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('task_option_task_id_fkey', 'task_option', 'task', ['task_id'], ['id'])
    op.drop_table('user_task_answer')
    # ### end Alembic commands ###
